<!-- START BREADCRUMB -->
<ul class="breadcrumb push-down-0">
	<li>&nbsp;</li>	
</ul>
<!-- END BREADCRUMB -->                                                

<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">
	<div class="row">
		<div class="col-md-12">			
	
			<div class="error-container">
				<div class="error-text"><?php echo $this->titulo; ?></div>
				<div class="error-subtext" style="text-align: justify !important;"><?php echo $this->mensagem; ?></div>
				<div class="error-actions">                                
					<div class="row">
						<div class="col-md-12">
							<a class="btn btn-info btn-block btn-lg" href="<?php echo $this->url('home'); ?>">
								Página Inicial
							</a>
						</div>
					</div>                                
				</div>				
			</div>			
			
		</div>
	</div>													
</div>                
<!-- END PAGE CONTENT WRAPPER -->