<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	<h3>Acesso Negado</h3>
</div>
<div class="modal-body">
	<div class="row">
		<div class="col-md-12">
			<div class="error-container">
				<div class="error-text"></div>
				
				<div class="alert alert-warning" role="alert">
							<strong>Acesso Negado!</strong>
							- Seu usuário não possui permissão para realizar essa operação.
						</div>			
			</div>
		</div>
	</div>
</div>
<div class="modal-footer">
	<button type="button" data-dismiss="modal" class="btn btn-primary pull-left">Fechar</button>
</div>


													