<?php
//plugins da tela
$this->headScript()->appendFile($this->basePath() . '/js/mylibs/jquery.autocomplete.js');
$this->headScript()->prependFile($this->basePath() . '/js/plugins/datatables/jquery.dataTables.min.js');

$this->headScript()->appendFile($this->basePath() . '/js/plugins/icheck/icheck.min.js');

$this->headScript()->appendFile($this->basePath() . '/js/plugins/bootstrap/bootstrap-datepicker.js');
$this->headScript()->appendFile($this->basePath() . '/js/plugins/bootstrap/bootstrap-select.js');
$this->headScript()->appendFile($this->basePath() . '/js/plugins/tagsinput/jquery.tagsinput.min.js');

//arquivos js basico para o form
$this->headScript()->appendFile($this->basePath() . '/js/app/form.js');
$this->headScript()->appendFile($this->basePath() . '/js/app/mascaras.js');

//arquivos js da tela
$this->headScript()->appendFile($this->basePath() . '/js/app/comercial/pedido/form.js');
//modal do form contato
$this->headScript()->appendFile($this->basePath() . '/js/app/comercial/pedido-produto/form.modal.js');



//inclui os arquivos CSS
//css do plugin autocomplete
$this->headLink()->appendStylesheet($this->basePath() . '/css/autocomplete.css');

//css da página
$this->headLink()->appendStylesheet($this->basePath() . '/css/app/default.table.css');

echo $this->headLink();
?>

<!-- START BREADCRUMB -->
<ul class="breadcrumb">
	<li><a href="#">Home</a></li>
	<li>Comercial</li>
	<li class="active"><a href="#">Pedido</a></li>
</ul>
<!-- END BREADCRUMB -->

<div class="page-title">
	<h2> <span class="fa fa-truck"></span> Pedido <small>Alterando registro</small></h2>
	<a href="<?php echo $this->url('comercial', 
									array('controller' => 'pedido')); ?>" class="btn btn-primary pull-right">
		<i class="fa fa-arrow-left"></i> Voltar
	</a>
</div>


<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">	
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			
			<!-- Exbibe mensagens do controller -->
			<?php echo $this->mensagens; ?>
			
			<!-- Ajax - retorno de mensagens -->
			<div id="ajaxReturn_Prospect"></div>
			
			<!-- URL para buscar informações via ajax -->
			<input type="hidden" id="ajax_getMsgDelContato" value=" <?php echo $this->url('comercial', array('controller' => 'prospect-contato', 'action' => 'get-msg-delete')); ?> " />
			<input type="hidden" id="ajax_getMsgDelProspect" value=" <?php echo $this->url('comercial', array('controller' => 'prospect', 'action' => 'get-msg-delete')); ?> " />
			<?php 
			$form = $this->form;
			$form->setAttribute('class', 'form-horizontal');
			$form->setAttribute('action', $this->url('comercial', array('controller' => 'pedido', 'action' => 'edit')));					
			$form->prepare();
			echo $this->form()->openTag($form);								
			?>
			
		
			
			<div class="panel panel-default tabs">
				<ul class="nav nav-tabs" role="tablist">
					<li class="active"><a href="#tab-principal" role="tab" data-toggle="tab">Dados Principais</a></li>
					<li><a href="#tab-produtos" role="tab" data-toggle="tab">Produtos</a></li>
				</ul>
				
				<div class="panel-body tab-content">
					<div class="tab-pane active" id="tab-principal">
						<div class="form-group">
							<?php echo $this->FormularioCampo($form, 'idPedido', 2); ?>
							<?php echo $this->FormularioCampo($form, '', 7); ?>
							<?php echo $this->FormularioCampo($form, 'Data', 3); ?>
						</div>
						<div class="form-group">
							<?php echo $this->FormularioCampo($form, 'Total', 3); ?>
						</div>
					</div> <!-- /#tab-principal -->
					
					
					<!-- Produtos -->
					<div class="tab-pane" id="tab-produtos">
						<p>Cadastre aqui os produtos deste pedido</p>

						<div class="form-group">
							<?php 
							$urlModalContato = $this->url('comercial', 
									array('controller' => 'pedido-produto', 
											'action' => 'get-form', 'id' => $this->idPedido));
							?>
							<a href="#" class="btn btn-primary pull-left showform_contato_new" data-link="<?php echo $urlModalContato; ?>">
								<i class="fa fa-gift"></i>
								Novo Produto
							</a>
						</div>	
							
						<!-- START DEFAULT DATATABLE -->
                        <div class="panel panel-info">
                        	<div class="panel-heading">                                
                            	<h3 class="panel-title">Lista de produtos</h3>
							</div>
                            <div class="panel-body" id="table_PedidoProduto">
                                <?php echo $this->tablePedidoProduto; ?>
                            </div>
						</div>
						<!-- END DEFAULT DATATABLE -->						
					</div> <!-- /#tab-contatos -->
					
			
				</div> <!-- /.panel-body .tab-content -->
				
				<!-- Actions -->
				<div class="panel-footer">
					<button class="btn btn-success pull-right">
						Salvar <span class="fa fa-floppy-o fa-right"></span>
					</button>
				</div>
			</div>
			<?php echo $this->form()->closeTag(); ?>
		</div>
	</div>
</div>
<!-- END PAGE CONTENT WRAPPER --> 
