<?php
// plugins js da tela
$this->headScript()->prependFile($this->basePath() . '/js/plugins/datatables/jquery.dataTables.min.js');
$this->headScript()->prependFile($this->basePath() . '/js/mylibs/jquery.dataTables.sort.js');

// arquivos js da tela
$this->headScript()->appendFile($this->basePath() . '/js/app/comercial/prospect/index.js');

// css da página
$this->headLink()->appendStylesheet($this->basePath() . '/css/app/default.table.css');
echo $this->headLink();
?>

<!-- START BREADCRUMB -->
<ul class="breadcrumb">
	<li><a href="#">Home</a></li>                    
	<li>Comercial</li>
	<li class="active"><a href="#">Pedido</a></li>
</ul>
<!-- END BREADCRUMB -->

<div class="page-title">
	<h2> <span class="fa fa-truck"></span> Pedido <small>Crie, altere, remova</small></h2>
	<a href="<?php echo $this->url('comercial', 
									array('controller' => 'pedido', 'action' => 'new')); ?>" class="btn btn-primary pull-right">
		<i class="fa fa-file-o"></i> Novo Pedido
	</a>
</div>

<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">
	
	<div class="row">
		<div class="col-md-12">	
			<!-- START DEFAULT DATATABLE -->
			<div class="panel panel-info">
				<div class="panel-heading">                                
					<h3 class="panel-title">Listando Pedidos</h3>					
				</div>
				<div class="panel-body">
					<div class="table-responsive">												
						<?php echo $this->tabela; ?>
					</div>
				</div>
			</div>
			<!-- END DEFAULT DATATABLE -->
		</div>
	</div>
	
</div>
<!-- END PAGE CONTENT WRAPPER -->