<?php
//plugins da tela
$this->headScript()->appendFile($this->basePath() . '/js/mylibs/jquery.autocomplete.js');

$this->headScript()->appendFile($this->basePath() . '/js/plugins/icheck/icheck.min.js');

$this->headScript()->appendFile($this->basePath() . '/js/plugins/bootstrap/bootstrap-datepicker.js');
$this->headScript()->appendFile($this->basePath() . '/js/plugins/bootstrap/bootstrap-select.js');
$this->headScript()->appendFile($this->basePath() . '/js/plugins/tagsinput/jquery.tagsinput.min.js');

//arquivos js basico para o form
$this->headScript()->appendFile($this->basePath() . '/js/app/form.js');
$this->headScript()->appendFile($this->basePath() . '/js/app/mascaras.js');

//arquivos js da tela
$this->headScript()->appendFile($this->basePath() . '/js/app/comercial/prospect/form.js');

//inclui os arquivos CSS
//css do plugin autocomplete
$this->headLink()->appendStylesheet($this->basePath() . '/css/autocomplete.css');
$this->headLink()->appendStylesheet($this->basePath() . '/css/theme-default.css');

echo $this->headLink();
?>

<!-- START BREADCRUMB -->
<ul class="breadcrumb">
	<li><a href="#">Home</a></li>
	<li>Comercial</li>
	<li class="active"><a href="#">Pedido</a></li>
</ul>
<!-- END BREADCRUMB -->

<div class="page-title">
	<h2> <span class="fa fa-truck"></span> Pedido <small>Criando novo registro</small></h2>
	<a href="<?php echo $this->url('comercial', 
									array('controller' => 'pedido')); ?>" class="btn btn-primary pull-right">
		<i class="fa fa-arrow-left"></i> Voltar
	</a>
</div>


<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">	
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			
			<!-- Exbibe mensagens do controller -->
			<?php echo $this->mensagens; ?>
			
			<?php 
			$form = $this->form;
			$form->setAttribute('class', 'form-horizontal');
			$form->setAttribute('action', $this->url('comercial', array('controller' => 'pedido', 'action' => 'new')));					
			$form->prepare();
			echo $this->form()->openTag($form);								
			?>
			
			
			
			<div class="panel panel-default tabs">
				<ul class="nav nav-tabs" role="tablist">
					<li class="active"><a href="#tab-principal" role="tab" data-toggle="tab">Dados Principais</a></li>
					<li><a href="#tab-produtos" role="tab" data-toggle="tab">Produtos</a></li>
					
				</ul>
				
				<div class="panel-body tab-content">
					<!-- Dados Principais -->
					<div class="tab-pane active" id="tab-principal">
						<div class="form-group">
							<?php echo $this->FormularioCampo($form, 'idPedido', 2); ?>
							<?php echo $this->FormularioCampo($form, '', 7); ?>
							<?php echo $this->FormularioCampo($form, 'Data', 3); ?>
						</div>
						
						
					</div> <!-- /#tab-principal -->
										

					<!-- Produtos -->
					<div class="tab-pane" id="tab-produtos">
						<div class="alert alert-info" role="alert">
							<strong>Produtos</strong>
							- Para cadastrar essas informações clique na aba "Dados Principais" informe os dados 
							e depois clique em "Salvar".
						</div>
					</div> <!-- /#tab-contatos -->
					
					
				</div> <!-- /.panel-body .tab-content -->
				
				<!-- Actions -->
				<div class="panel-footer">
					<button class="btn btn-success pull-right">
						Salvar <span class="fa fa-floppy-o fa-right"></span>
					</button>
				</div>
			</div>
			<?php echo $this->form()->closeTag(); ?>
		</div>
	</div>
</div>
<!-- END PAGE CONTENT WRAPPER --> 
