<!DOCTYPE html>
<html lang="pt-br" class="body-full-height">
<head>        
	<!-- META SECTION -->
    <?php echo $this->headTitle(); ?>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- END META SECTION -->
        
    <!-- Le styles -->
    <?php
    
	echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath () . '/img/favicon.ico'))
				->prependStylesheet($this->basePath() . '/css/theme-default.css');
	
	
	?>
</head>
<body>

	<?php echo $this->content; ?>	

	<!-- START PRELOADS -->
	<audio id="audio-alert" src="<?php echo $this->basePath(); ?>/audio/alert.mp3" preload="auto"></audio>
	<audio id="audio-fail" src="<?php echo $this->basePath(); ?>/audio/fail.mp3" preload="auto"></audio>
	<!-- END PRELOADS -->

	<!-- START SCRIPTS -->	
		<script src="<?php echo $this->basePath(). '/js/plugins/jquery/jquery.min.js'; ?>"></script>
		<script src="<?php echo $this->basePath(). '/js/plugins/jquery/jquery-ui.min.js'; ?>"></script>
		<script src="<?php echo $this->basePath(). '/js/plugins/bootstrap/bootstrap.min.js'; ?>"></script>
		
		<?php echo $this->headScript(); ?>
		
		<script src="<?php echo $this->basePath(). '/js/plugins.js'; ?>"></script>
		<script src="<?php echo $this->basePath(). '/js/actions.js'; ?>"></script>
    <!-- END SCRIPTS -->
</body>
</html>
