<link type="image/x-icon" href="/img/softwar-favicon.ico" rel="icon">
<?php
	echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath () . '/img/softwar-favicon.ico'))
				->appendStylesheet($this->basePath() . '/css/theme-default.css')
				->appendStylesheet($this->basePath() . '/css/app/default.css?v=1.1');
	//Testar Apple Icon
echo $this->headLink(array('rel' => 'apple-touch-icon',
			'href' => '/img/apple-touch-icon.png'));
	
	echo $this->headLink(array('rel' => 'apple-touch-icon',
			'href' => '/img/apple-touch-icon-60x60.png',
			'extras' => array('sizes' => '60x60')));
	
	echo $this->headLink(array('rel' => 'apple-touch-icon',
			'href' => '/img/apple-touch-icon-57x57.png',
			'extras' => array('sizes' => '57x57')));
	
	echo $this->headLink(array('rel' => 'apple-touch-icon',
			'href' => '/img/apple-touch-icon-144x144.png',
			'extras' => array('sizes' => '144x144')));
	
	echo $this->headLink(array('rel' => 'apple-touch-icon',
			'href' => '/img/apple-touch-icon-76x76.png',
			'extras' => array('sizes' => '76x76')));
	
	echo $this->headLink(array('rel' => 'apple-touch-icon',
			'href' => '/img/apple-touch-icon-152x152.png',
			'extras' => array('sizes' => '152x152')));
	
	echo $this->headLink(array('rel' => 'apple-touch-icon',
			'href' => '/img/apple-touch-icon-72x72.png',
			'extras' => array('sizes' => '72x72')));
	
	echo $this->headLink(array('rel' => 'apple-touch-icon',
			'href' => '/img/apple-touch-icon-114x114.png',
			'extras' => array('sizes' => '114x114')));
	
	echo $this->headLink(array('rel' => 'apple-touch-icon',
			'href' => '/img/apple-touch-icon-120x120.png',
			'extras' => array('sizes' => '120x120')));
	
	echo $this->headLink(array('rel' => 'apple-touch-icon',
			'href' => '/img/apple-touch-icon-precomposed.png'));
	
	echo $this->headLink(array('rel' => 'apple-touch-icon',
			'href' => '/img/apple-touch-icon-60x60-precomposed.png',
			'extras' => array('sizes' => '60x60')));
	
	echo $this->headLink(array('rel' => 'apple-touch-icon',
			'href' => '/img/apple-touch-icon-57x57-precomposed.png',
			'extras' => array('sizes' => '57x57')));
	
	echo $this->headLink(array('rel' => 'apple-touch-icon',
			'href' => '/img/apple-touch-icon-144x144-precomposed.png',
			'extras' => array('sizes' => '144x144')));
	
	echo $this->headLink(array('rel' => 'apple-touch-icon',
			'href' => '/img/apple-touch-icon-76x76-precomposed.png',
			'extras' => array('sizes' => '76x76')));
	
	echo $this->headLink(array('rel' => 'apple-touch-icon',
			'href' => '/img/apple-touch-icon-152x152-precomposed.png',
			'extras' => array('sizes' => '152x152')));
	
	echo $this->headLink(array('rel' => 'apple-touch-icon',
			'href' => '/img/apple-touch-icon-72x72-precomposed.png',
			'extras' => array('sizes' => '72x72')));
	
	echo $this->headLink(array('rel' => 'apple-touch-icon',
			'href' => '/img/apple-touch-icon-114x114-precomposed.png',
			'extras' => array('sizes' => '114x114')));
	
	echo $this->headLink(array('rel' => 'apple-touch-icon',
			'href' => '/img/apple-touch-icon-120x120-precomposed.png',
			'extras' => array('sizes' => '120x120')));
	
	

	echo $this->content; 
?>
        