<?php

$this->headScript()->appendFile($this->basePath() . '/js/plugins/bootstrap/bootstrap-select.js');
$this->headScript()->appendFile($this->basePath() . '/js/plugins/icheck/icheck.min.js');

$this->headLink()->appendStylesheet($this->basePath() . '/css/app/default.css');

?>

<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="#">Home</a></li>
    <li class="active">Dashboard</li>
</ul>
<!-- END BREADCRUMB -->

<div class="page-title">
    <h2>
        <span class="fa fa-comments"></span> Olá Usuário <small>Confira abaixo um pequeno resumo do dia</small>
    </h2>
</div>

<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">

    <!-- START WIDGETS -->
    <div class="row">

        <div class="col-md-4">
            <!-- START WIDGET CLOCK -->
            <div class="widget widget-danger widget-padding-sm">
                <div class="widget-big-int plugin-clock">00:00</div>
                <div class="widget-subtitle plugin-date">Loading...</div>
                <div class="widget-controls"></div>
                <div class="widget-buttons widget-c3">
                    <div class="col">
                        <a href="#"><span class="fa fa-clock-o"></span></a>
                    </div>
                    <div class="col">
                        <a href="#"><span class="fa fa-bell"></span></a>
                    </div>
                    <div class="col">
                        <a href="#"><span class="fa fa-calendar"></span></a>
                    </div>
                </div>
            </div>
            <!-- END WIDGET CLOCK -->
        </div>
        <div class="col-md-4">
            <!-- START WIDGET CLIENTES -->
            <div class="widget widget-default widget-item-icon">
                <div class="widget-item-left">
                    <span class="fa fa-truck"></span>
                </div>
                <div class="widget-data">
                    <div class="widget-int num-count"><?php echo $this->pedidos; ?></div>
                    <div class="widget-title">
                        <?php echo ('Pedidos'); ?>
                    </div>
                    
                </div>
                <div class="widget-controls"></div>
            </div>
            <!-- END WIDGET CLIENTES -->
        </div>
       
       
    </div>
    

  </div>
        <!-- END PAGE CONTENT WRAPPER -->